theme: jekyll-theme-minimal
title: Gamestate Interactive
logo: /assets/img/logo.png
description: London based mobile game development studio.
contact: contact@gamestate.io
google_analytics:
theme: jekyll-theme-minimal
